name: Test Suite

# Only triggers on pushes/PRs to master
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
    test:
        name: CI
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                dc: [dmd-latest, ldc-latest, dmd-master]
                arch: [x86, x86_64]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Install D compiler
              uses: dlang-community/setup-dlang@v2
              with:
                  compiler: ${{ matrix.dc }}

            - name: Run tests
              env:
                CONFIG: ${{matrix.config}}
                ARCH: ${{matrix.arch}}
                COMPILER: ${{matrix.dc}}
              shell: bash
              run: DC= ./travis-ci.sh

            - name: Upload PhantomCSS failures
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: phantomcss-failures
                overwrite: true
                path: |
                  test/screenshots/*.diff.png
                  test/screenshots/*.fail.png